#making calculator using python
floatnum1=float(input("Enter a num 1:\n"))
floatnum2=float(input("Enter a num 2:\n"))
print("Addition of two number is : " ,floatnum1-floatnum2)
print("\n")
print("Substraction of two number is : ",floatnum1-floatnum2)
print("\n")
print("Multiplication of two number is :",floatnum1*floatnum2)
print("\n")
print("Division of two number is : ",floatnum1/floatnum2)
print("\n")
print("Modulo of two number is : ",floatnum1%floatnum2)
print("\n")
print("Exponential of two number is : ",floatnum1**floatnum2)
