#variable conversion 
a=3
b=float(a)
c=["Ramendra","Ritesh","Rana_Pratap"]
d=("Ramendra","Ritesh","Rana_Pratap")
e={"Ramendra","Ritesh","Rana_Pratap"}
f={"Name":"Ramendra","Age":20}
g=set(c)
h=set(d)
i=tuple(e)
j=list(f)
print(a)
print("\n")
print(b)
print("\n")
print(c)
print("\n")
print(d)
print("\n")
print(e)
print("\n")
print(f)
print("\n")
# data type 
print(type(b))
print("\n")
print(type(g))
print("\n")
print(type(h))
print("\n")
print(type(i))
print("\n")
print(type(j))
print("\n")
l=complex(8,2)
print(type(l))
num=input("Enter number")
name=input("Enter name")
print(num)
print("\n")
print(name)
